export interface Surah {
  id: number;
  name: string;
  type: 'مكية' | 'مدنية';
  totalVerses: number;
}

export interface OReciter {
  id: string;
  name: string;
  server: string;
}

export const toArabicDigits = (num: number | string) => {
  return num.toString().replace(/\d/g, (d) => '٠١٢٣٤٥٦٧٨٩'[parseInt(d)]);
};

export const formatSurahId = (id: number) => id.toString().padStart(3, '0');

export const RECITERS: OReciter[] = [
  { id: '1', name: 'مشاري العفاسي', server: 'https://server8.mp3quran.net/afs/' },
  { id: '2', name: 'عبد الباسط عبد الصمد', server: 'https://server7.mp3quran.net/basit/' },
  { id: '3', name: 'محمود خليل الحصري', server: 'https://server13.mp3quran.net/husr/' },
  { id: '4', name: 'ماهر المعيقلي', server: 'https://server12.mp3quran.net/maher/' },
];

export const SURAHS: Surah[] = [
  { id: 1, name: 'الفاتحة', type: 'مكية', totalVerses: 7 },
  { id: 2, name: 'البقرة', type: 'مدنية', totalVerses: 286 },
  { id: 3, name: 'آل عمران', type: 'مدنية', totalVerses: 200 },
  { id: 4, name: 'النساء', type: 'مدنية', totalVerses: 176 },
  { id: 5, name: 'المائدة', type: 'مدنية', totalVerses: 120 },
  { id: 6, name: 'الأنعام', type: 'مكية', totalVerses: 165 },
  { id: 7, name: 'الأعراف', type: 'مكية', totalVerses: 206 },
  { id: 8, name: 'الأنفال', type: 'مدنية', totalVerses: 75 },
  { id: 9, name: 'التوبة', type: 'مدنية', totalVerses: 129 },
  { id: 10, name: 'يونس', type: 'مكية', totalVerses: 109 },
  { id: 11, name: 'هود', type: 'مكية', totalVerses: 123 },
  { id: 12, name: 'يوسف', type: 'مكية', totalVerses: 111 },
  { id: 13, name: 'الرعد', type: 'مدنية', totalVerses: 43 },
  { id: 14, name: 'إبراهيم', type: 'مكية', totalVerses: 52 },
  { id: 15, name: 'الحجر', type: 'مكية', totalVerses: 99 },
  { id: 16, name: 'النحل', type: 'مكية', totalVerses: 128 },
  { id: 17, name: 'الإسراء', type: 'مكية', totalVerses: 111 },
  { id: 18, name: 'الكهف', type: 'مكية', totalVerses: 110 },
  { id: 19, name: 'مريم', type: 'مكية', totalVerses: 98 },
  { id: 20, name: 'طه', type: 'مكية', totalVerses: 135 },
  { id: 21, name: 'الأنبياء', type: 'مكية', totalVerses: 112 },
  { id: 22, name: 'الحج', type: 'مدنية', totalVerses: 78 },
  { id: 23, name: 'المؤمنون', type: 'مكية', totalVerses: 118 },
  { id: 24, name: 'النور', type: 'مدنية', totalVerses: 64 },
  { id: 25, name: 'الفرقان', type: 'مكية', totalVerses: 77 },
  { id: 26, name: 'الشعراء', type: 'مكية', totalVerses: 227 },
  { id: 27, name: 'النمل', type: 'مكية', totalVerses: 93 },
  { id: 28, name: 'القصص', type: 'مكية', totalVerses: 88 },
  { id: 29, name: 'العنكبوت', type: 'مكية', totalVerses: 69 },
  { id: 30, name: 'الروم', type: 'مكية', totalVerses: 60 },
  { id: 31, name: 'لقمان', type: 'مكية', totalVerses: 34 },
  { id: 32, name: 'السجدة', type: 'مكية', totalVerses: 30 },
  { id: 33, name: 'الأحزاب', type: 'مدنية', totalVerses: 73 },
  { id: 34, name: 'سبأ', type: 'مكية', totalVerses: 54 },
  { id: 35, name: 'فاطر', type: 'مكية', totalVerses: 45 },
  { id: 36, name: 'يس', type: 'مكية', totalVerses: 83 },
  { id: 37, name: 'الصافات', type: 'مكية', totalVerses: 182 },
  { id: 38, name: 'ص', type: 'مكية', totalVerses: 88 },
  { id: 39, name: 'الزمر', type: 'مكية', totalVerses: 75 },
  { id: 40, name: 'غافر', type: 'مكية', totalVerses: 85 },
  { id: 41, name: 'فصلت', type: 'مكية', totalVerses: 54 },
  { id: 42, name: 'الشورى', type: 'مكية', totalVerses: 53 },
  { id: 43, name: 'الزخرف', type: 'مكية', totalVerses: 89 },
  { id: 44, name: 'الدخان', type: 'مكية', totalVerses: 59 },
  { id: 45, name: 'الجاثية', type: 'مكية', totalVerses: 37 },
  { id: 46, name: 'الأحقاف', type: 'مكية', totalVerses: 35 },
  { id: 47, name: 'محمد', type: 'مدنية', totalVerses: 38 },
  { id: 48, name: 'الفتح', type: 'مدنية', totalVerses: 29 },
  { id: 49, name: 'الحجرات', type: 'مدنية', totalVerses: 18 },
  { id: 50, name: 'ق', type: 'مكية', totalVerses: 45 },
  { id: 51, name: 'الذاريات', type: 'مكية', totalVerses: 60 },
  { id: 52, name: 'الطور', type: 'مكية', totalVerses: 49 },
  { id: 53, name: 'النجم', type: 'مكية', totalVerses: 62 },
  { id: 54, name: 'القمر', type: 'مكية', totalVerses: 55 },
  { id: 55, name: 'الرحمن', type: 'مدنية', totalVerses: 78 },
  { id: 56, name: 'الواقعة', type: 'مكية', totalVerses: 96 },
  { id: 57, name: 'الحديد', type: 'مدنية', totalVerses: 29 },
  { id: 58, name: 'المجادلة', type: 'مدنية', totalVerses: 22 },
  { id: 59, name: 'الحشر', type: 'مدنية', totalVerses: 24 },
  { id: 60, name: 'الممتحنة', type: 'مدنية', totalVerses: 13 },
  { id: 61, name: 'الصف', type: 'مدنية', totalVerses: 14 },
  { id: 62, name: 'الجمعة', type: 'مدنية', totalVerses: 11 },
  { id: 63, name: 'المنافقون', type: 'مدنية', totalVerses: 11 },
  { id: 64, name: 'التغابن', type: 'مدنية', totalVerses: 18 },
  { id: 65, name: 'الطلاق', type: 'مدنية', totalVerses: 12 },
  { id: 66, name: 'التحريم', type: 'مدنية', totalVerses: 12 },
  { id: 67, name: 'الملك', type: 'مكية', totalVerses: 30 },
  { id: 68, name: 'القلم', type: 'مكية', totalVerses: 52 },
  { id: 69, name: 'الحاقة', type: 'مكية', totalVerses: 52 },
  { id: 70, name: 'المعارج', type: 'مكية', totalVerses: 44 },
  { id: 71, name: 'نوح', type: 'مكية', totalVerses: 28 },
  { id: 72, name: 'الجن', type: 'مكية', totalVerses: 28 },
  { id: 73, name: 'المزمل', type: 'مكية', totalVerses: 20 },
  { id: 74, name: 'المدثر', type: 'مكية', totalVerses: 56 },
  { id: 75, name: 'القيامة', type: 'مكية', totalVerses: 40 },
  { id: 76, name: 'الإنسان', type: 'مدنية', totalVerses: 31 },
  { id: 77, name: 'المرسلات', type: 'مكية', totalVerses: 50 },
  { id: 78, name: 'النبأ', type: 'مكية', totalVerses: 40 },
  { id: 79, name: 'النازعات', type: 'مكية', totalVerses: 46 },
  { id: 80, name: 'عبس', type: 'مكية', totalVerses: 42 },
  { id: 81, name: 'التكوير', type: 'مكية', totalVerses: 29 },
  { id: 82, name: 'الانفطار', type: 'مكية', totalVerses: 19 },
  { id: 83, name: 'المطففين', type: 'مكية', totalVerses: 36 },
  { id: 84, name: 'الانشقاق', type: 'مكية', totalVerses: 25 },
  { id: 85, name: 'البروج', type: 'مكية', totalVerses: 22 },
  { id: 86, name: 'الطارق', type: 'مكية', totalVerses: 17 },
  { id: 87, name: 'الأعلى', type: 'مكية', totalVerses: 19 },
  { id: 88, name: 'الغاشية', type: 'مكية', totalVerses: 26 },
  { id: 89, name: 'الفجر', type: 'مكية', totalVerses: 30 },
  { id: 90, name: 'البلد', type: 'مكية', totalVerses: 20 },
  { id: 91, name: 'الشمس', type: 'مكية', totalVerses: 15 },
  { id: 92, name: 'الليل', type: 'مكية', totalVerses: 21 },
  { id: 93, name: 'الضحى', type: 'مكية', totalVerses: 11 },
  { id: 94, name: 'الشرح', type: 'مكية', totalVerses: 8 },
  { id: 95, name: 'التين', type: 'مكية', totalVerses: 8 },
  { id: 96, name: 'العلق', type: 'مكية', totalVerses: 19 },
  { id: 97, name: 'القدر', type: 'مدنية', totalVerses: 5 },
  { id: 98, name: 'البينة', type: 'مدنية', totalVerses: 8 },
  { id: 99, name: 'الزلزلة', type: 'مدنية', totalVerses: 8 },
  { id: 100, name: 'العاديات', type: 'مكية', totalVerses: 11 },
  { id: 101, name: 'القارعة', type: 'مكية', totalVerses: 11 },
  { id: 102, name: 'التكاثر', type: 'مكية', totalVerses: 8 },
  { id: 103, name: 'العصر', type: 'مكية', totalVerses: 3 },
  { id: 104, name: 'الهمزة', type: 'مكية', totalVerses: 9 },
  { id: 105, name: 'الفيل', type: 'مكية', totalVerses: 5 },
  { id: 106, name: 'قريش', type: 'مكية', totalVerses: 4 },
  { id: 107, name: 'الماعون', type: 'مكية', totalVerses: 7 },
  { id: 108, name: 'الكوثر', type: 'مكية', totalVerses: 3 },
  { id: 109, name: 'الكافرون', type: 'مكية', totalVerses: 6 },
  { id: 110, name: 'النصر', type: 'مدنية', totalVerses: 3 },
  { id: 111, name: 'المسد', type: 'مكية', totalVerses: 5 },
  { id: 112, name: 'الإخلاص', type: 'مكية', totalVerses: 4 },
  { id: 113, name: 'الفلق', type: 'مكية', totalVerses: 5 },
  { id: 114, name: 'الناس', type: 'مكية', totalVerses: 6 },
];
